on:
  repository_dispatch:
    types: [wheel-builder]
  workflow_dispatch:


jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        WINDOWS:
          - {ARCH: 'x86', WINDOWS: 'win32'}
          - {ARCH: 'x64', WINDOWS: 'win64'}
        PYTHON:
#          - {VERSION: "2.7", TOXENV: "py27", MSVC_VERSION: "2010"}
          - {VERSION: "3.5", TOXENV: "py35", MSVC_VERSION: "2019"}
#          - {VERSION: "3.6", TOXENV: "py36", MSVC_VERSION: "2019"}
#          - {VERSION: "3.7", TOXENV: "py37", MSVC_VERSION: "2019"}
#          - {VERSION: "3.8", TOXENV: "py38", MSVC_VERSION: "2019"}
    name: "Python ${{ matrix.PYTHON.VERSION }} on ${{ matrix.WINDOWS.WINDOWS }}"
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: ${{ matrix.PYTHON.VERSION }}
          architecture: ${{ matrix.WINDOWS.ARCH }}
        env:
          PIP_TRUSTED_HOST: pypi.python.org
      - name: Install MSVC for Python 2.7
        run: |
            Invoke-WebRequest -Uri https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi -OutFile VCForPython27.msi
            Start-Process msiexec -Wait -ArgumentList @('/i', 'VCForPython27.msi', '/qn', 'ALLUSERS=1')
            Remove-Item VCForPython27.msi -Force
        shell: powershell
        if: matrix.PYTHON.VERSION == '2.7'
      - run: pip install --index-url 'https://:2020-04-22T23:19:51.290101Z@time-machines-pypi.sealsecurity.io/' requests
      - name: Download OpenSSL
        run: |
            python .github/workflows/download_openssl.py ${{ matrix.WINDOWS.ARCH }}

      - run: pip install --index-url 'https://:2020-04-22T23:19:51.290101Z@time-machines-pypi.sealsecurity.io/' cffi six ipaddress "enum34; python_version < '3'"
      - run: echo %PATH%
      - name: Create Wheels
        run: set INCLUDE=D:\a\cryptography-5352\cryptography-5352\.github\workflows\openssl_zips\OpenSSL\include;%INCLUDE% && set LIB=D:\a\cryptography-5352\cryptography-5352\.github\workflows\openssl_zips\OpenSSL\lib;%LIB% && pip wheel . --wheel-dir=wheelhouse
#        env:
#          INCLUDE: D:\a\cryptography-5352\cryptography-5352\.github\workflows\openssl_zips\OpenSSL\include
#          LIB: D:\a\cryptography-5352\cryptography-5352\.github\workflows\openssl_zips\OpenSSL\lib
      - run: pip install --index-url 'https://:2020-04-22T23:19:51.290101Z@time-machines-pypi.sealsecurity.io/' -f wheelhouse --no-index cryptography
      - name: Print the OpenSSL we built and linked against
        run: |
            python -c "from cryptography.hazmat.backends.openssl.backend import backend;print('Loaded: ' + backend.openssl_version_text());print('Linked Against: ' + backend._ffi.string(backend._lib.OPENSSL_VERSION_TEXT).decode('ascii'))"

      - run: mkdir cryptography-wheelhouse
      - run: move wheelhouse\cryptography*.whl cryptography-wheelhouse\
      - uses: actions/upload-artifact@v1
        with:
          name: "cryptography-${{ github.event.client_payload.BUILD_VERSION }}-${{ matrix.WINDOWS.WINDOWS }}-${{ matrix.PYTHON.VERSION }}"
          path: cryptography-wheelhouse\